export const ROUTERS = {
  CLIENT: {
    HOME: "/",
    PRODUCTS: "/san-pham",
    PRODUCT_DETAIL: "/san-pham/:id",
    NEWS: "/tin-tuc",
    CONTACT: "/lien-he",
    CART: "/gio-hang",
    CHECKOUT: "/thanh-toan",
    LOGIN: "/dang-nhap",
    REGISTER: "/dang-ky",
    PROMOTION: "/khuyen-mai",
  },
  ADMIN: {
    HOME:       "/admin",
    USERS:      "/admin/nguoi-dung",
    PRODUCTS:   "/admin/danh-muc",
    VOUCHER:    "/admin/voucher",
    STORES:     "/admin/chuoi-cua-hang",
    STAFF:      "/admin/nhan-su",
    WAREHOUSE:  "/admin/kho-tong",
    STATISTICS: "/admin/thong-ke",
    MONITOR:    "/admin/giam-sat",
    ORDERS:     "/admin/don-hang",
  },
  STAFF: {
    HOME:       "/staff",
    ORDERS:     "/staff/don-hang",
    WAREHOUSE:  "/staff/kho-cuc-bo",
    TRANSFER:   "/staff/luan-chuyen",
    WARRANTY:   "/staff/bao-hanh",
    STATISTICS: "/staff/thong-ke",
  },
};
